# Generated by Django 4.1.4 on 2023-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagefields',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
